### ISSUE TITLE
Export fs/promises function for esm like you do for cjs

### ISSUE THREAD

**Issue by FreePhoenix888** [jprichardson/node-fs-extra#1008]
- **Operating System:**
- Ubuntu 22.04
- **Node.js version:**
- Node.js v18.14.0
- **`fs-extra` version:**
- fs-extra@11.1.1

Export fs/promises function for esm like you do for cjs

**Comment by RyanZim** [comment]
In CJS mode, we're exporting wrapped versions of graceful-fs which support either callbacks or promises. We can't do this in ESM, since exports are static. See https://github.com/jprichardson/node-fs-extra/issues/746 for detailed discussion.

We could `export * from 'fs/promises'`, but that wouldn't cover native sync methods, which would be confusing, because you'd have to import native sync methods from `fs`, but `fs-extra/esm` exports both sync and async methods.
