### ISSUE TITLE
Fails to move (rename) directory to non-empty directory even with clobber: true

### ISSUE THREAD

**Issue by darobin** [jprichardson/node-fs-extra#114]
The docs seem to indicate that `fs.move(dir, otherDir, { clobber: true })` will move a directory even if there is already content there. Looking at the code it seems that the intent is for that to work for files, it probably works for empty directories (that `rename()` is happy with) but it doesn't work for directories that have content. For that you need to `fs.remove()` them first. Maybe that's intentional (the tests don't exercise this case) but if so it should be documented as such.

**Comment by jprichardson** [comment]
Hmm. Good point. Do you think it makes sense to "move" a directory to a new directory that has content? It seems to me that should almost always produce an error. But since the functionality is provided for files, perhaps it should be possible for directories since the `{clobber: true}` makes the intent explicit. 

What are your thoughts on the proper behavior?

**Comment by darobin** [comment]
There are cases when you just want to overwrite the directory. In my situation, I have cases in which I can just regenerate a subset of the content, and others in which being smart is hopeless and I just generate a fresh copy to replace the old with. In the latter case I need to build the fresh copy in a temp dir and replace the live one. I'd say if you've specified clobber, you should get clobber :)

**Comment by jprichardson** [comment]
Thanks for the report. Fixed and published!
