### ISSUE TITLE
copySync can only copy directories not files

### ISSUE THREAD

**Issue by malei0311** [jprichardson/node-fs-extra#116]
I'm using node(v0.12.0)

**Comment by jprichardson** [comment]
Thanks for the report. I'll look into this next week (unless a PR is submitted before then).

**Comment by jprichardson** [comment]
Do you have code to reproduce this? Which OS? I only ask because of https://github.com/jprichardson/node-fs-extra/blob/master/test/copy-sync.test.js#L29

**Comment by malei0311** [comment]
*  os centos 6.2
*  node version v0.12.0

### code

if I didn't pass a callback parameter, it worked, [as #115](115)

```javascript
fs.copySync(sourceDir, destDir)
```

but, it didn't worked below

```javascript
fs.copySync(sourceDir, destDir, function(err){
})
```
`fs.copy` works fine

**Comment by jprichardson** [comment]
You don't pass a callback to the sync methods since they happen immediately and block the process. I think I'll update the documentation to make this clear.

**Comment by malei0311** [comment]
thx~

**Comment by awaldow** [comment]
Since at its core copyFileSync is using the normal node fs.(read|write)Sync methods you would deal with errors in copySync the same as with those, since copySync uses copyFileSync to do the real work anyways. It does a check for existence and explicitly throws an 'EEXISTS' error at the beginning but aside from that any other types of filesystem errors would (I assume) be thrown via the normal fs sync methods, which you should handle with try/catch.

**Comment by coryallegory** [comment]
I was snagged by the same issue, the documentation isn't clear on copySync's method signature, or maybe I misread it :S

Either way, it may be convenient to insert the try/catch to allow for copySync(src, dest, err) or something like that.

**Comment by jprichardson** [comment]
Documented `copySync()`. Thanks everyone.
