### ISSUE TITLE
Json file reading fails with 'utf8'

### ISSUE THREAD

**Issue by Edifice** [jprichardson/node-fs-extra#140]
When I call "fs.readJsonFileSync(path, 'utf8')", I get the following error:

    TypeError: Cannot use 'in' operator to search for 'throws' in utf8
        at Object.readFileSync (/Users/.../node_modules/fs-extra/node_modules/jsonfile/index.js:25:33)
        ...

OS: OS X Yosemite 10.10.3
Fs-extra: "0.18.4"

**Comment by jprichardson** [comment]
If you remove `'utf8`, do you get the same error?

**Comment by Edifice** [comment]
No, it works fine then (this is my workaround for now)
But I'm worried about it, when our project will support multiple languages, it might be a problem. (in the next couple of month)
And it might be a problem for others too.

**Comment by jprichardson** [comment]
Another workaround should be `{encoding: 'utf8'}`.

**Comment by jprichardson** [comment]
Ok, this has been fixed in `jsonfile@2.1.2`. Reinstall `fs-extra` to get the latest `jsonfile` version. In your case, `npm -i --save fs-extra@0.18.4`. Note: If you upgrade to `fs-extra@0.20.x`, the method `readJsonFileSync` does not exist anymore; you'll have to use `readJsonSync` which is the exact same.
