### ISSUE TITLE
ensureDir(dir, callback) second callback parameter not specified

### ISSUE THREAD

**Issue by lexatnet** [jprichardson/node-fs-extra#182]
second callback parameter not specified

```
fs.ensureDir(dir, function(err){
  //arguments.length ==2
})
```

**Comment by jprichardson** [comment]
I'm not sure what the issue is?

**Comment by jprichardson** [comment]
Closing, as not enough information provided. Please reopen if you would provide more info.

**Comment by triccardi-systran** [comment]
The issue is missing documentation on the arguments passed to all the callbacks.
This information is especially useful when using `fs-extra` in `async.waterfall` where we need to know in advance how many arguments there will be on the callback.

Should I open a new issue or could this one be re-open?

**Comment by jprichardson** [comment]
@triccardi-systran Makes sense. Done.

**Comment by RyanZim** [comment]
Going to close this as a dupe of https://github.com/jprichardson/node-fs-extra/issues/349. https://github.com/jprichardson/node-fs-extra/issues/349 is newer, but it addresses the whole problem.
