### ISSUE TITLE
remove function executes "successfully" but doesn't do anything?

### ISSUE THREAD

**Issue by georgeedwards** [jprichardson/node-fs-extra#281]
I am using the remove function, which when executed prints "success" to the console. But as you can see below the file path is unchanged. Why? I am using the latest version on Windows 10. 

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/DIwJh.png

**Comment by jprichardson** [comment]
I'm not sure what you're trying to do here... specifically since you're using `copy` right after `remove` with the same path. Also, you're using absolute paths, so that seems weird given the path name.

If you're trying to test if `remove` works, just use `remove` and then call `existsSync` on that path.

**Comment by georgeedwards** [comment]
@jprichardson The remove was for a child directory of the one listed, the idea being to remove something from `docs-production` and then move what remains elsewhere. I changed it to show in the screenshot. However, I still don't understand why `docs-production- still exists in `pre-source` after running this file?

**Comment by jprichardson** [comment]
> However, I still don't understand why docs-production- still exists inpre-source` after running this file?

You're using absolute paths. That's why. e.g. `/pre-source` vs `pre-source`.
