### ISSUE TITLE
Edit copy-dev-null test description

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#370]
In the unit test https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/__tests__/copy-dev-null.test.js#L22, `it` says "should error" but it seems like we test for a successful copy operation. Which one was intended, error or copying a file with size 0?

**Comment by RyanZim** [comment]
@manidlou I was wondering about that one too, it seems that there was some back-and-forth on the behavior in the past: https://github.com/jprichardson/node-fs-extra/issues/193, https://github.com/jprichardson/node-fs-extra/commit/631ed20f7bd8a817346073efa59f93f19c77da48, https://github.com/jprichardson/node-fs-extra/pull/204, https://github.com/jprichardson/node-fs-extra/commit/d874b3bb5bba40da3a85d6286d2bc677d0a2ea0e.

@jprichardson What's the expected behavior here, and why?

**Comment by jprichardson** [comment]
So it looks like before #204, it should error, then, given #204 - it was modified to not error. I honestly don't know the proper behavior. I'm assuming that it probably should not error, but what would be the real world use case for copying `/dev/null`?

**Comment by RyanZim** [comment]
> what would be the real world use case for copying /dev/null?

I can't think of one.

**Comment by RyanZim** [comment]
I'd say, just edit the test description to match the test.

**Comment by manidlou** [comment]
> what would be the real world use case for copying /dev/null?

I can't think of one neither at this moment.

> I'd say, just edit the test description to match the test. :+1: 

Definitely agreed.

**Comment by manidlou** [comment]
Resolved. See #371.
