### ISSUE TITLE
Commit 9bef553728ec2a44f0c02d3a42bc118e5d72b4eb breaks compatibility with node < 5.10.0

### ISSUE THREAD

**Issue by frankdannhauer** [jprichardson/node-fs-extra#389]
Buffer.alloc was introduced in node 5.10.0 (https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding)

The engines.node entry in package.json should reflect this.

**Comment by RyanZim** [comment]
@frankdannhauer Actually, `Buffer.alloc` was added in [v6.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-04-26-version-600-current-jasnell). It was backported to the v5.x line in v5.10.0, and backported to the v4.x line in [v4.5.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#2016-08-15-version-450-argon-lts-thealphanerd).

The `engines` field is up-to-date, since it specifies v4.5.0+. Easy to see how someone could be confused by this, though.
