### ISSUE TITLE
I thinks we should add d.ts to this awesome module to make better dev experience

### ISSUE THREAD

**Issue by ulivz** [jprichardson/node-fs-extra#468]
As we all know, most of the popular modules in JS community own the `d.ts` type declaration file, Shouldn't we also work for it ?

Just we want to use this module to replace the native file system. we should got it.

**Comment by RyanZim** [comment]
You can already install the types with [`@types/fs-extra`](https://www.npmjs.com/package/@types/fs-extra).

**Comment by ulivz** [comment]
I think you misunderstand my thought, I just don't want to dev for TypeScript, Just in webstorm, the native `fs` module owns all the  API prompt, but when I study to use `fs-extra`, there are no prompt anymore. So, I throw out this issue.

Why no any prompt? 
> Just in the source code, we used `assign` that no IDE can trace the API, but if you list the `typings` property in the `package.json`, and link to the `index.d.ts`, everything will be beautiful.

**Comment by franklinyu** [comment]
From [official documentation](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html):

> There are two main ways you can publish your declaration files to npm:
>
> 1. bundling with your npm package, or
> 2. publishing to the [@types organization](https://www.npmjs.com/~types) on npm.
>
> If you control the npm package you are publishing declarations for, then the first approach is favored. That way, your declarations and JavaScript always travel together.

It would be great if typings can be maintained by library maintainers; that way API declaration can be kept up-to-date.

**Comment by RyanZim** [comment]
I frankly do not have the bandwidth or knowledge to maintain the typings. However, I have already opened an issue after we made large breaking changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16183. If somebody wants to watch this repo and update the typings as needed, they're more than welcome to.

**Comment by dustingraham** [comment]
Understandable. Thank you for mentioning @types/fs-extra, I had not heard of definitely typed before. Looks pretty cool.

Just tried it, and phpstorm/webstorm will now type hint and help with the `fs.ensureDir` type commands. However, navigating to the definition goes to the type export, it doesn't find the underlying code in the node_modules folder.

So, I think there's still benefit to improving this. But, I understand not wanting it in the repo since none of the maintainers are familiar with it. Thanks for a great library.
