### ISSUE TITLE
remove() doesn't delete a subfolder inside my project folder. What is wrong here ?

### ISSUE THREAD

**Issue by RyanHannan** [jprichardson/node-fs-extra#532]
- **Operating System:**  Win 10 64 bit
- **Node.js version:**  8.7.0
- **`fs-extra` version:** 5.0.0

I am trying to delete a non-empty subfolder which is inside my project directory but i can't seem to delete it with fs.remove(folderPath). The code runs with no errors but the folder is still there and i can't even delete it manually unless i first empty the folder and delete all the files in there. I get a permission related error when i try to directly delete the folder even though i am the owner/admin. Could it be a permissions related issue ?

**Comment by RyanZim** [comment]
Might be permissions; not sure.

**Comment by RyanZim** [comment]
@RyanHannan are you still having this issue?

**Comment by mojavelinux** [comment]
I'm seeing a similar problem on Windows. Every now and again in the test suite, it fails to remove a directory because it claims the directory is not empty. But when the process completes, the directory is gone. So could it be that there's a race condition or that it's a false warning?

```
Error: ENOTEMPTY: directory not empty, rmdir ..
at Object.fs.rmdirSync (fs.js:846:18)
at rmkidsSync (node_modules\fs-extra\lib\remove\rimraf.js:304:27)
```

**Comment by Inve1951** [comment]
having this issue right now
`fs.removeSync("lib")`
```
Error: ENOTEMPTY: directory not empty, rmdir '........\lib\subfolder'
    at Object.fs.rmdirSync (fs.js:856:18)
```

**Comment by mojavelinux** [comment]
I've found that the only way to fix this is to put the remove operation in a loop (with a timeout) until it succeeds. It always seems to succeed after a few milliseconds.

**Comment by Inve1951** [comment]
in my case it fixed itself after trying other stuff and reverting

**Comment by mojavelinux** [comment]
For me, the problem always comes back. When I use it across a test suite of 500 methods, it fails maybe 2 times.

**Comment by RyanZim** [comment]
@mojavelinux Do you have this issue when using https://github.com/isaacs/rimraf instead of `fse.remove`?

**Comment by mojavelinux** [comment]
@RyanZim Yes, it does seem to be a problem with rimraf. That's where it always dies.

I get something that looks like this:

```js
Error: EBUSY: resource busy or locked, rmdir 'C:\projects\antora-odh8j\packages\cli\test\work'
  at Object.fs.rmdirSync (fs.js:846:18)
  at rmdirSync (node_modules\fs-extra\lib\remove\rimraf.js:276:13)
  at Object.rimrafSync (node_modules\fs-extra\lib\remove\rimraf.js:252:7)
  at Context.after (packages\cli\test\cli-test.js:79:10)
```

I've even tried rimraf directly and saw no improvement.

I have been very careful to ensure that no files or directories are locked. Windows just seems to be very unreliable at removing directories.

My only solution has been to use an infinite loop until Windows decides it actually wants to do what it was asked to do.

**Comment by Inve1951** [comment]
I find it more likely that the fault is with node/v8 rather than windows. I looked into it for a bit but my understanding of node's codebase it too bad to find anything in there.
As per [MSDN](//msdn.com/aa365488): `The RemoveDirectory function marks a directory for deletion on close. Therefore, the directory is not removed until the last handle to the directory is closed.` and thus provide an alternate interface for deleting the folder content as well.

**Comment by Inve1951** [comment]
What about `childProcess.execSync("rd /s /q " + foldername)`?
Never had that issue in msbatch files.
@RyanZim @mojavelinux

**Comment by manidlou** [comment]
@Inve1951 shelling out is not recommended as it can cause security issues.

**Comment by Inve1951** [comment]
@manidlou how so?

**Comment by manidlou** [comment]
@Inve1951 it can lead to issues like command injection.

https://hackernoon.com/nodejs-security-issue-javascript-node-example-tutorial-vulnerabilities-hack-line-url-command-injection-412011924d1b

 `childProcess.exec()` is [a bash interpreter, not a program launcher](https://blog.liftsecurity.io/2014/08/19/Avoid-Command-Injection-Node.js/).

**Comment by Inve1951** [comment]
oh of course. nvm then

**Comment by RyanZim** [comment]
It seems we've never been able to pin this down concretely; so I'm gonna close this out. Happy to reopen if we figure out how to consistently reproduce.

**Comment by agilgur5** [comment]
@RyanZim I was able to reproduce this with some frequency while writing integration tests for `rollup-plugin-typescript2` in https://github.com/ezolenko/rollup-plugin-typescript2/pull/371 .
I added a small timeout (1s) to workaround this issue with `remove` on [this line](https://github.com/ezolenko/rollup-plugin-typescript2/blob/61d78bd2f3fcf2ad5707086f152bc6c93e6d0715/__tests__/integration/errors.spec.ts#L18).

Without that timeout, I was getting the error mentioned above (`Error: ENOTEMPTY: directory not empty, rmdir`) about 25-50% of the time running tests.
Since a tiny timeout helps, this definitely seems like a race condition. I call `fs.remove` in the test's `afterAll`, so I don't believe it has to do with Jest's parallelization either. 

> As per [MSDN](//msdn.com/aa365488): `The RemoveDirectory function marks a directory for deletion on close. Therefore, the directory is not removed until the last handle to the directory is closed.` and thus provide an alternate interface for deleting the folder content as well.

Read [this](https://github.com/jprichardson/node-fs-extra/issues/532#issuecomment-366681440) older comment made me think that perhaps the file handles have not quite been closed when the tests finish, and that causes `remove` to fail, but I'm not sure.

I can try to make a more minimal repro of this if needed, though TBD if it'll actually show up minimally
