### ISSUE TITLE
`copy` does not preserve file ownership and permissons

### ISSUE THREAD

**Issue by cadorn** [jprichardson/node-fs-extra#54]

**Comment by jprichardson** [comment]
One step closer: https://github.com/jprichardson/node-fs-extra/commit/082aa7f4ba95fd05f186c31cba7f3af61328f9a2 Preserving modes is fixed.

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-fs-extra/releases/tag/0.22.0

**Comment by H8to** [comment]
@jprichardson 
Hi there, sorry to bump an old issue. I'm trying to find the root cause why Atom text editor, which is using node-fs-extra to copy/duplicate directories, does not preserve the permissions.
This is the issue I'm referring to: [tree-view #1218](https://github.com/atom/tree-view/issues/1218)

I gave my best to get an understanding of what happens during the copy-job but phew..
As pentester I do not have deep understanding of programming coffee-script, js or similar.

```js
if (initialPathIsDirectory) {
              results.push(catchAndShowFileErrors((function(_this) {
                return function() {
                  fs.copySync(initialPath, newPath);
                  return _this.emitter.emit('entry-copied', {
                    initialPath: initialPath,
                    newPath: newPath
                  });
                };
              })(this)));
```
from `/usr/lib/atom/node_modules/tree-view/lib/tree-view.js`

They seem to use the fs.copySync function which should preserve the permissions as per the changelogs of node-fs-extra:
``` 
0.11.1 / 2014-09-02
-------------------
- bugfix `copySync()` preserve file permissions [#80][#80]
```

Atom makers and I would be thankful for any help!
