### ISSUE TITLE
Suggest: how about add updateFile method?

### ISSUE THREAD

**Issue by lovetingyuan** [jprichardson/node-fs-extra#550]
it is just an advise:
how about add updateFile method?
```javascript
fs.updateFile(path, function (originalContent) {
  return newContent;
});
```

**Comment by RyanZim** [comment]
The API you're proposing wouldn't be optimal, because after returning the new content, you'd have no way of knowing whether the file update worked (i.e. no error handling, or knowing when it's complete).

Honestly, I think this is just sugar on top of something that's already pretty easy to do (especially with promises or async/await), and therefore shouldn't be added.
