### ISSUE TITLE
`moveSync` copies and deletes dirs on external drives

### ISSUE THREAD

**Issue by garyking** [jprichardson/node-fs-extra#608]
- **Operating System:** macOS 10.13.5 (17F77)
- **Node.js version:** v8.11.2
- **`fs-extra` version:** 7.0.0

I'm using `moveSync` to rename a big folder on an external drive. The folder is about 2 GB. It seems like `moveSync` copies the folder then deletes the original, rather than simply renaming the folder, since it takes a few minutes to finish. 

I thought that it was supposed to use [rename](https://github.com/jprichardson/node-fs-extra/pull/549) under the hood, but it seems like that's not the case for me, since when I replace `moveSync` with `renameSync`, the rename is instant.

The path to the folder I'm renaming is `/Volumes/Data/Test/One`, if it matters.

**Comment by RyanZim** [comment]
@garyking `move` falls back to copy-and-delete if `rename` fails. Not sure why it failed in this case, though.

**Comment by manidlou** [comment]
hmm.. @RyanZim we updated `move` implementation to use `rename` as the main operation but somehow we forgot to update the `moveSync` implementation! I kind of blame myself on that as I was supposed to do that! I will be working on updating `moveSync` this weekend.

In the meantime, @garyking in order to be a little ahead of ourselves, will you please try your code with `move()` and tell us if it works?!

**Comment by garyking** [comment]
I confirmed that `moveSync` copies then deletes the old file, whereas `move` is an instant rename.
