### ISSUE TITLE
Suggestion: add inputFile as complement to outputFile

### ISSUE THREAD

**Issue by johnpyp** [jprichardson/node-fs-extra#705]
I think it would be nice to have an `fs.inputFile` function that would work like `fs.outputFile`, except that this function would create a missing file and read it, rather than write it. Similar functionality to this:

```
const inputFile = async (path, ...args) => {
  await fs.ensureFile(path)

  return fs.readFile(path, ...args)
}
```

**Comment by RyanZim** [comment]
So it would read an empty file if it doesn't exist?

Also this raises the question of whether there should be an `fs.inputJson`, and if so, what that would read.

**Comment by johnpyp** [comment]
Yeah, the idea would be it eliminates the need to catch readFile misses or to preempt them with a `fs.ensureFile`. I'm not sure what the best approach to `fs.inputJson` would be, maybe an empty object or array? I'm not sure if it is necessary, given there isn't a `fs.ensureJson` function either.

**Comment by RyanZim** [comment]
I guess I'm not sure how frequent this is needed.

**Comment by johnpyp** [comment]
I'm not sure how frequent this is needed either, as it is pretty much just a convenience function.

I think it would be nice to not only have this, but have a function like this as a complement to all the of the `ensure` functions, for example a combined `fs.ensureDir` and `fs.readdir`.

**Comment by paragi** [comment]
IMO  fs-extra, is all about convenience. 
If it was built for for performance, it would be another matter. 

As an example, take outpuFile: ensureDir is called each time, before readFile writeFile,  adding a lot of IO heavy overhead for small files.
If fs-extra was build for performance, ensureDir should only be called if readFile failed. Also asynchronous protection of objects would be ensured, in the most effective manner.  
I get that it makes a "nice" and understandable flow of the module code. But otherwise it has no benefit to the user. 

With that in mind, i think it would look good with symmetrical input/output functions.

**Comment by RyanZim** [comment]
I'm not seeing much use for this, going to close as an edge-case.
