### ISSUE TITLE
Move fails with EPERM when destination is in root of drive

### ISSUE THREAD

**Issue by ZudoB** [jprichardson/node-fs-extra#819]
- **Operating System:** Windows 10 1909
- **Node.js version:** 14.2.0
- **`fs-extra` version:** 9.0.1

Moving a file or directory where the destination is in the root of a drive (e.g. `D:\filename`) causes the operation to fail, as the move function attempts to mkdir the root of the drive.

```js
const fs = require("fs-extra");
fs.moveSync("D:\\Source.txt", "D:\\Destination\\SomeFolder"); // succeeds
fs.moveSync("D:\\Source.txt", "D:\\Destination"); // fails
```

Error is as follows:

```
Uncaught Error: EPERM: operation not permitted, mkdir 'D:\'
    at Object.mkdirSync (fs.js:940:3)
    at module.exports.makeDirSync (---\node_modules\fs-extra\lib\mkdirs\make-dir.js:101:15)
    at Object.moveSync (---\node_modules\fs-extra\lib\move-sync\move-sync.js:16:3) {
  errno: -4048,
  syscall: 'mkdir',
  code: 'EPERM',
  path: 'D:\\'
}
```

**Comment by RyanZim** [comment]
Huh, that's a bug; looks like we need to either check if the parent is root, or else have proper handling of an `EPERM` error here: https://github.com/jprichardson/node-fs-extra/blob/96facaae988ad665ce5c5fe1998154c75af31ddc/lib/move/move.js#L24

@manidlou what's your preference?

**Comment by manidlou** [comment]
That's actually documented (https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback). I would say we check the error, but if anyone thinks checking if parent is root is a better approach because of specific reasons, I am open to that!

**Comment by RyanZim** [comment]
We will need to check for root either way most likely, because we can't consider all `EPERM` errors to be as a result of root. The question is whether we pre-emptively check for root, or check after we get `EPERM`. As for the choice between those two, if we need to hit the FS to check root, do it after we get the error, to keep it fast for all other cases; if we can just do a static path check, perhaps we can check before calling `mkdirp`.

To be perfectly clear here, I'm not in favor of changing the way `mkdirp` works here, I just think `move` should handle this better.

**Comment by RyanZim** [comment]
Interestingly enough, `copy` doesn't have this problem, because it does an explicit `pathExists` call before calling `mkdirs`: https://github.com/jprichardson/node-fs-extra/blob/96facaae988ad665ce5c5fe1998154c75af31ddc/lib/copy/copy.js#L41-L51

Not sure if that's ideal, though. Anytime you use `pathExists`, you have race condition potential.

**Comment by manidlou** [comment]
Is it enough to use `path.parse()` to get the root and check if that's the same as the parent?

**Comment by RyanZim** [comment]
@manidlou That's a good idea! It should work, though I'm not sure, we might need to do some slash normalization.

**Comment by manidlou** [comment]
hmm.. I actually just remembered that moving to the root would basically fail because of permission error (unless you run it with `sudo`) at least on unix like systems, but I guess things are different in windows! That makes writing tests for this a bit tricky!

**Comment by RyanZim** [comment]
@manidlou it'd be perfectly fine to write a test that's skipped on all platforms other than Windows for this. Any progress here?

**Comment by RyanZim** [comment]
@manidlou what's the status here?

**Comment by RyanZim** [comment]
I'd like to ship v10 next week, looks like this will need to be pushed back.

**Comment by manidlou** [comment]
Sorry @RyanZim! been super busy! I plan to wrap this up this weekend. If I cannot manage to do that, we will leave it for v11.
