### ISSUE TITLE
writeFile should accept a stream, like node:fs/promises now allows

### ISSUE THREAD

**Issue by Arro** [jprichardson/node-fs-extra#977]
- **Operating System:** macOS Ventura 13.0 (22A380)
- **Node.js version:** 16.18.0
- **`fs-extra` version:** 10.1.0

Attempting to write a stream to a file using `fs-extra`, my code looks like this:

```
import os from "os"
import path from "path"

import fs from "fs-extra"

const some_location = path.join(os.tmpdir(), `.some-file.json`)
await fs.writeFile(some_location, some_stream)

// result:
// TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of IncomingMessage
```

Nowadays, I can do it with node.js:

```
import os from "os"
import path from "path"

import { writeFile } from "node:fs/promises"

const some_location = path.join(os.tmpdir(), `.some-file.json`)
await writeFile(some_location, some_stream)

// result:
// [it writes the file]
```

Seeing as `fs-extra` is attempting to be "node.js' fs, but enhanced", should this be added to `fs-extra`?

**Comment by RyanZim** [comment]
`fs-extra` currently adds promise support to the existing callback API (we added this before `fs/promises` was a thing). Since fs-extra uses graceful-fs under the hood, we can't use `fs/promises` as graceful-fs doesn't yet support it (see https://github.com/isaacs/node-graceful-fs/issues/160). If you want this functionality, we suggest using `fs/promises` directly.
