### ISSUE TITLE
fs.copy() incorrect async behavior

### ISSUE THREAD

**Issue by malinges** [jprichardson/node-fs-extra#98]
`fs.copy()` seems to have a incorrect async behavior. In some circumstances, the callback is called somewhat randomly: it may be called once, but also twice, three times, or even never.

Here is a basic working example of this issue: https://gist.github.com/malinges/c9d48ffaf8fa940e4df3

This behavior showed up while I was using [grunt-docco](https://github.com/DavidSouther/grunt-docco), which wraps [docco](https://github.com/jashkenas/docco), which itself uses `fs-extra`. I noticed some files weren't copied properly with `fs.copy()`, in a purely random fashion (files were either correctly written, empty, or missing).
See the original issue here: DavidSouther/grunt-docco#40.

Let me know if you need more info.

**Comment by jprichardson** [comment]
Yeah, it should be a nice reference, thank you. 

The plan moving forward is for me to include a file walker and then build `copy` on top of that. Ultimately, `mkdirs` and `remove()` will be as well, but that's further on down the line. Glob functionality would be awesome as well, but that's even further on down the line.

I've started by including the tests from `ncp` as seen here: https://github.com/jprichardson/node-fs-extra/tree/master/test/ncp as the more test coverage we have, the better. If anyone is willing, it'd be helpful to know why the "skipped" (https://github.com/jprichardson/node-fs-extra/blob/master/test/ncp/ncp.js#L175 and https://github.com/jprichardson/node-fs-extra/blob/master/test/ncp/ncp.js#L184) are failing.

**Comment by adam-lynch** [comment]
@jprichardson do you have a rough ETA on your rewrite? Sounds like it would take awhile

**Comment by jprichardson** [comment]
> @jprichardson do you have a rough ETA on your rewrite? Sounds like it would take awhile

Unfortunately, no. I think it will take awhile. The first step is to build a walker, probably a hybrid of https://github.com/daaku/nodejs-walker and https://github.com/thlorenz/readdirp

**Comment by robogeek** [comment]
FYI - https://www.npmjs.com/package/globfs

**Comment by jprichardson** [comment]
OK, I've forked `ncp` into `fs-extra`. Will be looking into this next...

**Comment by jprichardson** [comment]
This has been fixed. Unfortunately, I don't have an automated test to reproduce it. You can verify that this fix does indeed work by doing the following:

Clone the gist from @DavidSouther above. Create a bash script with the following:

```bash
#!/usr/bin/env bash

node copytest1.js
echo ""
```

then in bash run:

```bash
while ./runtest; do :; done
```

You'll see a bunch of clustered:

```
done: { '0': null }
done: { '0': null }
```

The behavior that we want is:

```
done: { '0': null }

done: { '0': null }

done: { '0': null }

done: { '0': null }
```

basically indicating that a callback was only called once.

Ok, so now that verifies that `ncp@1.0.1` is broken. Now to substitute `fs-extra` by modifiying:

**copytest1.js**:

from:

```js
require("ncp").copy("node_modules/docco/resources/parallel/", "parallel", function(err, res) { console.log("done:", arguments); });
```

to

```js
require("fs-extra").copy("node_modules/docco/resources/parallel/", "parallel", function(err, res) { console.log("done:", arguments); });
```

Checkout git commit https://github.com/jprichardson/node-fs-extra/commit/a9b98eea4257a863f66e844e5fcd004ecea29bb3

then run:

```bash
while ./runtest; do :; done
```

you'll see the same behavior as `ncp`.

Finally checkout this latest commit: https://github.com/jprichardson/node-fs-extra/commit/35345a330fedfd2aaab54471d1db9cbcdc087a94

then run:

```bash
while ./runtest; do :; done
```

You'll see the expected behavior.

I'd love it if anyone could submit a test for this. I've been staring at this code for too long today. Glad it's finally fixed though :)

**Comment by overlookmotel** [comment]
Has this not been fixed in ncp? Seems like a serious bug and something the maintainers would want to do something about...

But nice one @jprichardson for fixing it in fs-extra. Can your fix also patch ncp?

**Comment by jprichardson** [comment]
> Has this not been fixed in ncp? 

Sadly it hasn't. 

> Seems like a serious bug and something the maintainers would want to do something about...

Totally agree.

> Can your fix also patch ncp?

Yes it's just simply: https://github.com/jprichardson/node-fs-extra/commit/35345a330fedfd2aaab54471d1db9cbcdc087a94. But the ncp maintainers have shown that they're no long interested in maintaining `ncp` and that's why I felt forced to bring the `ncp` code into this module.

**Comment by overlookmotel** [comment]
What a ball-ache! Seems like ncp is depended on by a lot of other modules.

**Comment by overlookmotel** [comment]
Did you try issuing a PR on ncp?

**Comment by jprichardson** [comment]
> Did you try issuing a PR on ncp?

No because they've been ignoring pretty all of them within the last two months. So I figured there wasn't much of a point.

**Comment by overlookmotel** [comment]
Fair enough! It's a shame. Least they could do is put something in the README saying the module is no longer maintained.

To my eyes, ncp's coding style is pretty convoluted, so I'm not entirely surprised this kind of bug has crept in.

**Comment by sdnetwork** [comment]
For me the problem appear in ncp when options.modified have been added 
https://github.com/AvianFlu/ncp/commit/85cd50a5736f009cb2b50ac2a090542eb27b7e9c

so it appears since the ncp 1.0.0 version, if i have understand the problem.
but in my project i use the 0.5.0 version, and today i have the same behaviour some file are empty, not copied.

i can't reproduce but it is just to ask if you are sure that fix this problem :
  
    I noticed some files weren't copied properly with fs.copy(), in a purely random fashion (files were either correctly written, empty, or missing).

**Comment by jprichardson** [comment]
@sdnetwork does it work with `fs-extra@0.18.0`?
